/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    testimonials: Testimonial;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    header: Header;
    footer: Footer;
    chatSettings: ChatSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    chatSettings: ChatSettingsSelect<false> | ChatSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Las páginas del sitio. Cada página se arma con secciones (bloques). Tocá «Vista previa» para ver los cambios en vivo antes de publicar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Nombre interno de la página (no siempre se muestra en el sitio).
   */
  title: string;
  /**
   * Parte final de la URL. Usá "home" para la portada; ej.: "about", "work-with-me/private-sessions". Cambiarlo cambia el enlace de la página.
   */
  slug: string;
  /**
   * Armá la página agregando secciones. Arrastralas para reordenar.
   */
  layout?:
    | (
        | {
            variant?: ('split' | 'fullBleed') | null;
            eyebrow?: string | null;
            heading: string;
            lede?: string | null;
            image?: (number | null) | Media;
            imageSide?: ('right' | 'left') | null;
            ctas?:
              | {
                  label?: string | null;
                  variant?: ('primary' | 'secondary' | 'whatsapp') | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Qué tan ancho se ve el texto. Estrecho = más cómodo de leer.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            lede?: string | null;
            image?: (number | null) | Media;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'threePhases';
          }
        | {
            heading: string;
            image?: (number | null) | Media;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            closing?: string | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'situations';
          }
        | {
            image: number | Media;
            eyebrow?: string | null;
            /**
             * Optional short line over the photo.
             */
            caption?: string | null;
            height?: ('standard' | 'tall') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoBand';
          }
        | {
            heading: string;
            cards?:
              | {
                  image?: (number | null) | Media;
                  title: string;
                  body: string;
                  ctaLabel?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'waysGrid';
          }
        | {
            heading?: string | null;
            items?: (number | Testimonial)[] | null;
            reviewsLabel?: string | null;
            reviewsUrl?: string | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            image?: (number | null) | Media;
            imageSide?: ('left' | 'right') | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitImageText';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signatureBand';
          }
        | {
            heading: string;
            body?: string | null;
            ctas?:
              | {
                  label?: string | null;
                  variant?: ('primary' | 'secondary' | 'whatsapp') | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            align?: ('center' | 'left') | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Qué tan ancho se ve el texto. Estrecho = más cómodo de leer.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            /**
             * Anchor id, e.g. immersive
             */
            anchor?: string | null;
            title: string;
            /**
             * e.g. "Signature"
             */
            tag?: string | null;
            tagline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            included?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            investment?: string | null;
            cta: {
              label?: string | null;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
              id?: string | null;
            };
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formatDetail';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            intro?: string | null;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Qué tan ancho se ve el texto. Estrecho = más cómodo de leer.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            heading: string;
            intro?: string | null;
            leftTitle?: string | null;
            left?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            rightTitle?: string | null;
            right?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnLists';
          }
        | {
            tiles?:
              | {
                  title: string;
                  line?: string | null;
                  value?: string | null;
                  ctaLabel?: string | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactTiles';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            /**
             * Fondo de la sección. Alterná claro/arena para dar ritmo; «noche» para tramos oscuros.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
      )[]
    | null;
  /**
   * Lo que aparece en Google. Ideal ≤ 60 caracteres.
   */
  metaTitle?: string | null;
  /**
   * Resumen que aparece bajo el título en Google. Ideal ≤ 155 caracteres.
   */
  metaDescription?: string | null;
  /**
   * Imagen que se ve al compartir la página en redes (WhatsApp, Facebook…).
   */
  ogImage?: (number | null) | Media;
  /**
   * Si lo activás, la página no aparece en Google ni en el mapa del sitio.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Todas las fotos del sitio. Subí una imagen y usala en cualquier página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describí la imagen en pocas palabras (accesibilidad y SEO). Ej: «Sabine guiando una sesión de respiración».
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Reseñas y testimonios que aparecen en las páginas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * El texto de la reseña.
   */
  quote: string;
  /**
   * De dónde viene, ej. "Google Review".
   */
  source?: string | null;
  /**
   * Nombre o iniciales del cliente.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Los artículos del blog. Escribí el contenido, subí una imagen de portada y publicá. Tocá «Vista previa» para verlo en vivo antes de publicar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * El título del artículo, tal como se muestra en el sitio.
   */
  title: string;
  /**
   * Parte final de la URL del artículo, ej.: "breathing-into-grief". El artículo vive en /blog/<dirección>/.
   */
  slug: string;
  /**
   * Fecha que se muestra y que ordena el blog. Si la dejás vacía, se usa la fecha de creación.
   */
  publishedAt?: string | null;
  /**
   * Ruta del artículo en el sitio anterior, para los redirects. No editar.
   */
  oldPath?: string | null;
  /**
   * Imagen principal del artículo (arriba del texto y en las tarjetas del blog).
   */
  heroImage?: (number | null) | Media;
  /**
   * Uno o dos renglones que resumen el artículo. Se muestra en la lista del blog.
   */
  excerpt?: string | null;
  /**
   * El cuerpo del artículo. Podés agregar títulos, párrafos, listas e imágenes.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo que aparece en Google. Ideal ≤ 60 caracteres. Si lo dejás vacío se usa el título.
   */
  metaTitle?: string | null;
  /**
   * Resumen que aparece bajo el título en Google. Ideal ≤ 155 caracteres. Si lo dejás vacío se usa el resumen.
   */
  metaDescription?: string | null;
  /**
   * Imagen al compartir en redes. Si lo dejás vacío se usa la portada.
   */
  ogImage?: (number | null) | Media;
  /**
   * Si lo activás, el artículo no aparece en Google ni en el mapa del sitio.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Quién puede entrar a administrar el sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              lede?: T;
              image?: T;
              imageSide?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              width?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        threePhases?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lede?: T;
              image?: T;
              body?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        situations?:
          | T
          | {
              heading?: T;
              image?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              closing?: T;
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        photoBand?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              caption?: T;
              height?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        waysGrid?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    body?: T;
                    ctaLabel?: T;
                    href?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              heading?: T;
              items?: T;
              reviewsLabel?: T;
              reviewsUrl?: T;
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        splitImageText?:
          | T
          | {
              image?: T;
              imageSide?: T;
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        signatureBand?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              heading?: T;
              body?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              align?: T;
              tone?: T;
              width?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        formatDetail?:
          | T
          | {
              anchor?: T;
              title?: T;
              tag?: T;
              tagline?: T;
              body?: T;
              included?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              investment?: T;
              cta?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              note?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              width?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnLists?:
          | T
          | {
              heading?: T;
              intro?: T;
              leftTitle?: T;
              left?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rightTitle?: T;
              right?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        contactTiles?:
          | T
          | {
              tiles?:
                | T
                | {
                    title?: T;
                    line?: T;
                    value?: T;
                    ctaLabel?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              heading?: T;
              intro?: T;
              tone?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  oldPath?: T;
  heroImage?: T;
  excerpt?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  source?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Marca, contacto, redes y mensajes de WhatsApp que usa todo el sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  slogan?: string | null;
  description?: string | null;
  email?: string | null;
  phoneDisplay?: string | null;
  /**
   * Digits only, for wa.me links.
   */
  whatsappNumber?: string | null;
  instagram?: string | null;
  googleReviews?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  /**
   * Pre-filled message per CTA context.
   */
  whatsappMessages?:
    | {
        context: string;
        message: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Enlaces del menú de arriba del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Enlaces dentro del desplegable «Work With Me».
   */
  workWithMe?:
    | {
        label: string;
        href: string;
        /**
         * Micro-copy opcional bajo el enlace en el submenú.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enlaces dentro del desplegable «Retreats».
   */
  retreats?:
    | {
        label: string;
        href: string;
        /**
         * Micro-copy opcional bajo el enlace en el submenú.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Enlaces sueltos de la barra superior (ej.: The Method, Blog, About, Contact).
   */
  primary?:
    | {
        label: string;
        href: string;
        /**
         * Micro-copy opcional bajo el enlace en el submenú.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Enlaces y textos del pie del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandBlurb?: string | null;
  locationBlurb?: string | null;
  subBrandTitle?: string | null;
  subBrandName?: string | null;
  subBrandBlurb?: string | null;
  workWithMe?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  explore?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  newsletterBlurb?: string | null;
  legal?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  bottomNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Asistente de chat con IA para visitantes. Responde solo sobre el contenido del sitio y ofrece contacto directo por WhatsApp con Sabine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatSettings".
 */
export interface ChatSetting {
  id: number;
  /**
   * Si lo apagas, vuelve el botón flotante de WhatsApp.
   */
  enabled?: boolean | null;
  /**
   * Clave de https://openrouter.ai/settings/keys. Nunca se muestra en el sitio público.
   */
  openRouterApiKey?: string | null;
  /**
   * Los modelos marcados GRATIS no consumen crédito de OpenRouter.
   */
  model?: string | null;
  /**
   * Primer mensaje que ve el visitante al abrir el chat.
   */
  welcomeMessage?: string | null;
  /**
   * Ajustes de tono o reglas extra para el asistente.
   */
  extraInstructions?: string | null;
  /**
   * Datos que no están en el sitio (precios, horarios, políticas…). El asistente los usará al responder.
   */
  extraKnowledge?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  slogan?: T;
  description?: T;
  email?: T;
  phoneDisplay?: T;
  whatsappNumber?: T;
  instagram?: T;
  googleReviews?: T;
  linkedin?: T;
  facebook?: T;
  whatsappMessages?:
    | T
    | {
        context?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  workWithMe?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  retreats?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandBlurb?: T;
  locationBlurb?: T;
  subBrandTitle?: T;
  subBrandName?: T;
  subBrandBlurb?: T;
  workWithMe?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  explore?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  newsletterBlurb?: T;
  legal?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bottomNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatSettings_select".
 */
export interface ChatSettingsSelect<T extends boolean = true> {
  enabled?: T;
  openRouterApiKey?: T;
  model?: T;
  welcomeMessage?: T;
  extraInstructions?: T;
  extraKnowledge?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}