/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    testimonials: Testimonial;
    subscribers: Subscriber;
    inquiries: Inquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    header: Header;
    footer: Footer;
    chatSettings: ChatSetting;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    chatSettings: ChatSettingsSelect<false> | ChatSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Your website pages. Each page is built from sections (blocks). Tap 'Preview' to see your changes live before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal name for the page (it isn't always shown on the site).
   */
  title: string;
  /**
   * The last part of the URL. Use "home" for the front page; e.g. "about", "work-with-me/private-sessions". Changing it changes the page link.
   */
  slug: string;
  /**
   * Build the page by adding sections. Drag them to reorder.
   */
  layout?:
    | (
        | {
            variant?: ('split' | 'fullBleed') | null;
            eyebrow?: string | null;
            heading: string;
            lede?: string | null;
            /**
             * Short scannable line under the description, e.g. "Small-group retreat · Tulum · November to April".
             */
            metaLine?: string | null;
            image?: (number | null) | Media;
            /**
             * Vimeo or YouTube link. Plays silently on a loop behind the headline. Leave it empty and the photo above is used instead.
             */
            videoUrl?: string | null;
            /**
             * Optional. Cuts the loop short so it never runs past a good moment.
             */
            videoTrim?: number | null;
            /**
             * The shape the photo is cut into. Leave the section without a photo and the text simply runs full width, with no empty shape.
             */
            imageShape?: ('arch' | 'rounded' | 'square') | null;
            /**
             * How much air sits between the menu and the start of this section.
             */
            spacing?: ('compact' | 'normal' | 'generous') | null;
            imageSide?: ('right' | 'left') | null;
            /**
             * Over the photo, or underneath it so the footage stays clean.
             */
            textPlacement?: ('over' | 'below') | null;
            ctas?:
              | {
                  label?: string | null;
                  variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Small label above the heading, e.g. "YOUR INVITATION".
             */
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Centres the heading and the body together.
             */
            align?: ('left' | 'center') | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * How wide the text appears. Narrow = easier to read.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            lede?: string | null;
            /**
             * Short scannable line under the description, e.g. "Small-group retreat · Tulum · November to April".
             */
            metaLine?: string | null;
            image?: (number | null) | Media;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'threePhases';
          }
        | {
            heading: string;
            image?: (number | null) | Media;
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            closing?: string | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'situations';
          }
        | {
            image: number | Media;
            eyebrow?: string | null;
            /**
             * Optional short line over the photo.
             */
            caption?: string | null;
            height?: ('standard' | 'tall') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoBand';
          }
        | {
            /**
             * Large background image. Used as the poster if a video is set.
             */
            image: number | Media;
            /**
             * Full screen fills the whole screen on desktop with the text over the photo. Portrait shows the photo upright and complete, with the text beside it. Both keep the current height on phones.
             */
            format?: ('fullScreen' | 'portrait' | 'band') | null;
            /**
             * Optional video (Vimeo/YouTube link, or a direct .mp4). Shows instead of the image — space for drone footage.
             */
            videoUrl?: string | null;
            eyebrow?: string | null;
            heading?: string | null;
            body?: string | null;
            ctas?:
              | {
                  label?: string | null;
                  variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaFeature';
          }
        | {
            heading: string;
            cards?:
              | {
                  image?: (number | null) | Media;
                  title: string;
                  body: string;
                  ctaLabel?: string | null;
                  href?: string | null;
                  /**
                   * Auto shares the row evenly with the other cards. Use Full width for a card that should stand on its own, like a newsletter sign-up.
                   */
                  width?: ('auto' | 'half' | 'full') | null;
                  /**
                   * The dark wash over the photo that keeps the white text readable. Lighter shows more of the photo; check the text still reads.
                   */
                  overlay?: ('light' | 'medium' | 'strong') | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'waysGrid';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            /**
             * Add photos. Drag to reorder. They lay out in a responsive grid.
             */
            images?:
              | {
                  image: number | Media;
                  /**
                   * Optional caption.
                   */
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * How wide the text appears. Narrow = easier to read.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            /**
             * Compact, scannable facts. Label on the left, value on the right.
             */
            rows?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * How wide the text appears. Narrow = easier to read.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'detailsGrid';
          }
        | {
            heading: string;
            /**
             * Chapters show in order. Tick "Hidden behind Read more" to fold one into the expandable part. Leave every box unticked to show them all as plain sections.
             */
            chapters?:
              | {
                  title?: string | null;
                  body?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  collapsed?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Text of the expand link, e.g. "Read more".
             */
            moreLabel?: string | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * How wide the text appears. Narrow = easier to read.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'expandableStory';
          }
        | {
            heading?: string | null;
            items?: (number | Testimonial)[] | null;
            reviewsLabel?: string | null;
            reviewsUrl?: string | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | {
            image?: (number | null) | Media;
            imageSide?: ('left' | 'right') | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitImageText';
          }
        | {
            eyebrow?: string | null;
            heading: string;
            body?: string | null;
            image?: (number | null) | Media;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signatureBand';
          }
        | {
            heading: string;
            body?: string | null;
            ctas?:
              | {
                  label?: string | null;
                  variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            align?: ('center' | 'left') | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * How wide the text appears. Narrow = easier to read.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            /**
             * Anchor id, e.g. immersive
             */
            anchor?: string | null;
            title: string;
            /**
             * e.g. "Signature"
             */
            tag?: string | null;
            tagline?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * e.g. "YOUR RETREAT EXPERIENCE".
             */
            includedLabel?: string | null;
            included?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Small print below the list, e.g. the lunch condition.
             */
            includedNote?: string | null;
            investment?: string | null;
            cta: {
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
              id?: string | null;
            };
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formatDetail';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading: string;
            intro?: string | null;
            /**
             * Simple list is one line per item. Numbered stages gives each item its own card with a big gold number, a headline and a paragraph — for steps that happen in order.
             */
            layout?: ('list' | 'stages') | null;
            items?:
              | {
                  /**
                   * Only used by the Numbered stages layout. Leave empty for a simple list.
                   */
                  title?: string | null;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            cta: {
              enabled?: boolean | null;
              label?: string | null;
              variant?: ('primary' | 'gold' | 'secondary' | 'whatsapp') | null;
              action: 'whatsapp' | 'internal' | 'email' | 'external';
              whatsappContext?:
                | (
                    | 'general'
                    | 'foundation'
                    | 'immersive'
                    | 'oneDayPrivate'
                    | 'couples'
                    | 'personalizedRetreat'
                    | 'curated'
                    | 'corporate'
                    | 'signature'
                    | 'discoveryCall'
                    | 'contact'
                  )
                | null;
              /**
               * e.g. /the-method/ or #immersive (internal) or full https URL.
               */
              href?: string | null;
            };
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * How wide the text appears. Narrow = easier to read.
             */
            width?: ('narrow' | 'default' | 'wide') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            heading: string;
            intro?: string | null;
            leftTitle?: string | null;
            left?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            rightTitle?: string | null;
            right?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnLists';
          }
        | {
            tiles?:
              | {
                  title: string;
                  line?: string | null;
                  value?: string | null;
                  ctaLabel?: string | null;
                  action: 'whatsapp' | 'internal' | 'email' | 'external';
                  whatsappContext?:
                    | (
                        | 'general'
                        | 'foundation'
                        | 'immersive'
                        | 'oneDayPrivate'
                        | 'couples'
                        | 'personalizedRetreat'
                        | 'curated'
                        | 'corporate'
                        | 'signature'
                        | 'discoveryCall'
                        | 'contact'
                      )
                    | null;
                  /**
                   * e.g. /the-method/ or #immersive (internal) or full https URL.
                   */
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactTiles';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            subjectLabel?: string | null;
            /**
             * The options someone can pick. Drag to reorder. Leave empty to use the standard list.
             */
            subjects?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            buttonLabel?: string | null;
            /**
             * A link to the privacy policy is added automatically at the end.
             */
            finePrint?: string | null;
            /**
             * What someone sees once they have signed up, in place of the form.
             */
            successMessage?: string | null;
            /**
             * Shown in italics right after the message.
             */
            successSignature?: string | null;
            align?: ('left' | 'center') | null;
            /**
             * Section background. Alternate light/sand for rhythm; use “night” for darker stretches.
             */
            tone?: ('cream' | 'sand' | 'night') | null;
            /**
             * Optional anchor id for #links (e.g. inquiry).
             */
            anchor?: string | null;
            /**
             * Keeps the section saved but removes it from the live site.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
      )[]
    | null;
  /**
   * What shows up in Google. Ideally 60 characters or fewer.
   */
  metaTitle?: string | null;
  /**
   * The summary that shows under the title in Google. Ideally 155 characters or fewer.
   */
  metaDescription?: string | null;
  /**
   * The image shown when the page is shared on social media (WhatsApp, Facebook…).
   */
  ogImage?: (number | null) | Media;
  /**
   * If you turn this on, the page won't appear in Google or the sitemap.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * All the site's photos. Upload an image and use it on any page. Best results: at least 2400px wide and under 3 MB. If a photo is heavier, shrink it at tinypng.com first — it keeps the quality and cuts the weight.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in a few words (for accessibility and SEO). E.g. 'Sabine guiding a breathwork session'.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Reviews and testimonials shown across the pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The text of the review.
   */
  quote: string;
  /**
   * Where it comes from, e.g. "Google Review".
   */
  source?: string | null;
  /**
   * The client's name or initials.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The blog articles. Write the content, upload a cover image, and publish. Tap 'Preview' to see it live before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The article title, exactly as it shows on the site.
   */
  title: string;
  /**
   * The last part of the article URL, e.g. "breathing-into-grief". The article lives at /blog/<address>/.
   */
  slug: string;
  /**
   * The date shown and used to order the blog. If you leave it empty, the creation date is used.
   */
  publishedAt?: string | null;
  /**
   * The article's path on the old site, used for redirects. Don't edit.
   */
  oldPath?: string | null;
  /**
   * The article's main image (above the text and on the blog cards).
   */
  heroImage?: (number | null) | Media;
  /**
   * One or two lines that summarize the article. Shown in the blog list.
   */
  excerpt?: string | null;
  /**
   * The body of the article. You can add headings, paragraphs, lists, and images.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What shows up in Google. Ideally 60 characters or fewer. If left empty, the title is used.
   */
  metaTitle?: string | null;
  /**
   * The summary that shows under the title in Google. Ideally 155 characters or fewer. If left empty, the summary is used.
   */
  metaDescription?: string | null;
  /**
   * The image shown when shared on social media. If left empty, the cover image is used.
   */
  ogImage?: (number | null) | Media;
  /**
   * If you turn this on, the article won't appear in Google or the sitemap.
   */
  noindex?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Everyone who signed up through the site. Newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  firstName?: string | null;
  /**
   * Which page they signed up from.
   */
  source?: string | null;
  /**
   * Empty means it is stored here but not yet in the email platform.
   */
  syncedAt?: string | null;
  /**
   * Why the last sync failed, if it did.
   */
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everything sent through a form on the site. Newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message?: string | null;
  /**
   * Tick it once you have answered.
   */
  handled?: boolean | null;
  /**
   * Which page the form was on.
   */
  source?: string | null;
  /**
   * When the alert email went out. Empty means email is not configured yet.
   */
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can log in to manage the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              lede?: T;
              metaLine?: T;
              image?: T;
              videoUrl?: T;
              videoTrim?: T;
              imageShape?: T;
              spacing?: T;
              imageSide?: T;
              textPlacement?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              align?: T;
              tone?: T;
              width?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        threePhases?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lede?: T;
              metaLine?: T;
              image?: T;
              body?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        situations?:
          | T
          | {
              heading?: T;
              image?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              closing?: T;
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        photoBand?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              caption?: T;
              height?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        mediaFeature?:
          | T
          | {
              image?: T;
              format?: T;
              videoUrl?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        waysGrid?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    image?: T;
                    title?: T;
                    body?: T;
                    ctaLabel?: T;
                    href?: T;
                    width?: T;
                    overlay?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              intro?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              tone?: T;
              width?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        detailsGrid?:
          | T
          | {
              heading?: T;
              rows?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              note?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              width?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        expandableStory?:
          | T
          | {
              heading?: T;
              chapters?:
                | T
                | {
                    title?: T;
                    body?: T;
                    collapsed?: T;
                    id?: T;
                  };
              moreLabel?: T;
              tone?: T;
              width?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              heading?: T;
              items?: T;
              reviewsLabel?: T;
              reviewsUrl?: T;
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        splitImageText?:
          | T
          | {
              image?: T;
              imageSide?: T;
              heading?: T;
              body?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        signatureBand?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              image?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              heading?: T;
              body?: T;
              ctas?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              align?: T;
              tone?: T;
              width?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        formatDetail?:
          | T
          | {
              anchor?: T;
              title?: T;
              tag?: T;
              tagline?: T;
              body?: T;
              includedLabel?: T;
              included?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              includedNote?: T;
              investment?: T;
              cta?:
                | T
                | {
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              tone?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              heading?: T;
              intro?: T;
              layout?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              note?: T;
              cta?:
                | T
                | {
                    enabled?: T;
                    label?: T;
                    variant?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                  };
              tone?: T;
              width?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnLists?:
          | T
          | {
              heading?: T;
              intro?: T;
              leftTitle?: T;
              left?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rightTitle?: T;
              right?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        contactTiles?:
          | T
          | {
              tiles?:
                | T
                | {
                    title?: T;
                    line?: T;
                    value?: T;
                    ctaLabel?: T;
                    action?: T;
                    whatsappContext?: T;
                    href?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              subjectLabel?: T;
              subjects?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              heading?: T;
              intro?: T;
              buttonLabel?: T;
              finePrint?: T;
              successMessage?: T;
              successSignature?: T;
              align?: T;
              tone?: T;
              anchor?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  oldPath?: T;
  heroImage?: T;
  excerpt?: T;
  body?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noindex?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  source?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  source?: T;
  syncedAt?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  handled?: T;
  source?: T;
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Brand, contact, social links, and WhatsApp messages used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  brandName?: string | null;
  slogan?: string | null;
  description?: string | null;
  /**
   * Changes every headline on the site at once, keeping the proportion between pages. Headlines already shrink on their own on phones; this shifts the whole scale up or down.
   */
  headingScale?: ('compact' | 'normal' | 'generous') | null;
  email?: string | null;
  phoneDisplay?: string | null;
  /**
   * Digits only, for wa.me links.
   */
  whatsappNumber?: string | null;
  instagram?: string | null;
  googleReviews?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  /**
   * Pre-filled message per CTA context.
   */
  whatsappMessages?:
    | {
        context: string;
        message: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Links for the site's top menu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Links inside the "Work With Me" dropdown.
   */
  workWithMe?:
    | {
        label: string;
        href: string;
        /**
         * Optional micro-copy shown under the link in the submenu.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Links inside the "Retreats" dropdown.
   */
  retreats?:
    | {
        label: string;
        href: string;
        /**
         * Optional micro-copy shown under the link in the submenu.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  couples?:
    | {
        label: string;
        href: string;
        /**
         * Optional micro-copy shown under the link in the submenu.
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Standalone top-bar links (e.g. The Method, Blog, About, Contact).
   */
  primary?:
    | {
        label: string;
        href: string;
        /**
         * Optional micro-copy shown under the link in the submenu.
         */
        description?: string | null;
        /**
         * Keeps the link out of the top bar on a computer, where space is tight, and shows it in the phone menu, where there is room.
         */
        mobileOnly?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Links and text for the site footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandBlurb?: string | null;
  locationBlurb?: string | null;
  subBrandTitle?: string | null;
  subBrandName?: string | null;
  subBrandBlurb?: string | null;
  workWithMe?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  explore?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  newsletterBlurb?: string | null;
  /**
   * What someone sees once they have signed up, in place of the form.
   */
  newsletterSuccess?: string | null;
  /**
   * Shown in italics right after the message.
   */
  newsletterSignature?: string | null;
  legal?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  bottomNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * AI chat assistant for visitors. It answers only about the site's content and offers direct WhatsApp contact with Sabine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatSettings".
 */
export interface ChatSetting {
  id: number;
  /**
   * Turn it off to bring back the floating WhatsApp button.
   */
  enabled?: boolean | null;
  /**
   * Key from https://openrouter.ai/settings/keys. Never shown on the public site.
   */
  openRouterApiKey?: string | null;
  /**
   * Models marked FREE don't use up your OpenRouter credit.
   */
  model?: string | null;
  /**
   * The first message a visitor sees when they open the chat.
   */
  welcomeMessage?: string | null;
  /**
   * Tone tweaks or extra rules for the assistant.
   */
  extraInstructions?: string | null;
  /**
   * Details that aren't on the site (prices, schedules, policies…). The assistant will use them when answering.
   */
  extraKnowledge?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  slogan?: T;
  description?: T;
  headingScale?: T;
  email?: T;
  phoneDisplay?: T;
  whatsappNumber?: T;
  instagram?: T;
  googleReviews?: T;
  linkedin?: T;
  facebook?: T;
  whatsappMessages?:
    | T
    | {
        context?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  workWithMe?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  retreats?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  couples?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        id?: T;
      };
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        description?: T;
        mobileOnly?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandBlurb?: T;
  locationBlurb?: T;
  subBrandTitle?: T;
  subBrandName?: T;
  subBrandBlurb?: T;
  workWithMe?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  explore?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  newsletterBlurb?: T;
  newsletterSuccess?: T;
  newsletterSignature?: T;
  legal?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bottomNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatSettings_select".
 */
export interface ChatSettingsSelect<T extends boolean = true> {
  enabled?: T;
  openRouterApiKey?: T;
  model?: T;
  welcomeMessage?: T;
  extraInstructions?: T;
  extraKnowledge?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}